<div class="row">
  <div class="col-md-12">
   <div class="x_panel" style="height: 850px;">
      <div class="x_title">
        <h2><i class="fa fa-bars"></i> Laporan Pemakaian BBM <small>Float left</small></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">


        <div class="" role="tabpanel" data-example-id="togglable-tabs">
          <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
            <li role="presentation" class="active"><a href="#tab_penjualan" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Penjualan</a>
            </li>
            </ul>
          <div id="myTabContent" class="tab-content"> 
            <div role="tabpanel" class="tab-pane fade active in" id="tab_penjualan" aria-labelledby="home-tab">
                <div class="row" style="margin-bottom: 30px;margin-left: 0px;">
                     <p class="lead">Pemakaian BBM</p>
                       <p>Menunjukkan setiap transaksi pemakaian BBM untuk secara keseluruhan, informasinya adalah termasuk tanggal, jumlah dan total</p>
                      <a type="button" class="btn btn-default" href="<?php echo base_url(); ?>lprUmum/pdf_pemakaianBBM">Lihat Laporan</a>
              </div>  
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
      </div>
    </div>
  </div>